### ISSUE TITLE
If during load, the Xref Entity is not found, disable or hide the 'delete' Xref Entity button.

### ISSUE THREAD

**Issue by mscottsewell** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#1]
I was confused when I connected this plugin to a brand new instance and there was no 'create' button, only a 'delete' button.  (I then realized once you click 'create records it prompts you to create the entity.)

Not a big deal, just something to clean up next time you're 'in' this code.

**Comment by MscrmTools** [comment]
As usual, thank for the feedback! I will update this soon

**Comment by MscrmTools** [comment]
ready for release
