### ISSUE TITLE
IT killed my connection

### ISSUE THREAD

**Issue by pb1051** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#10]
My IT department killed my connection to Dynamics through XRMToolBox, is there any way to run this process inside my implementation? I have the Power BI Option Set XRef entity created in my instance from a few years ago, but it's outdated.

**Comment by MscrmTools** [comment]
@pb1051 not sure to understand what you need

**Comment by pb1051** [comment]
@MscrmTools Update my Power BI Option Set XRef entity without XRMToolBox.

**Comment by MscrmTools** [comment]
You can take the code from this repository to make your own. Or you can update records manually as it's only a Dynamics entity to fill
