### ISSUE TITLE
Error creating entity

### ISSUE THREAD

**Issue by kxjc** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#13]
I'm using the latest version of the tool and being met with this error when trying to create the entity. 
![image](https://github.com/MscrmTools/GapConsulting.PowerBIOptionSetAssistant/assets/61426371/93f1116b-eb00-42ae-a59a-9bb4bc548b50)

If I try to create it again, I see the following error about missing columns.

![image](https://github.com/MscrmTools/GapConsulting.PowerBIOptionSetAssistant/assets/61426371/8ae67236-c2c5-46f0-938d-092297a75906)

I've tried the following without any luck..
- deleting the entity and creating again (multiple times)
- removing the CRM toolbox from appdata and 'reinstalling'
- manually create the missing columns as mentioned in the error but there are a lot more missing that needed recreation. still didn't work after that as the types and options are probably not correct. 
- attempted to create the entity in different environments within the organization

Any advice and suggestions are appreciated. Thanks!

**Comment by redmondChris** [comment]
Was this issue fixed, or just closed? I just experienced the same error messages shown above, using version 1.2021.2.4 of PowerBI Option-Set Assistant. In PowerBI, I can use Get data > Dataverse to find gap_ powerbioptionsetrefs as an entity, but when I select it, I get an "Invalid table name" error in the preview pane. Using Power Apps, I can't find the gap_ powerbioptionsetrefs entity, but I do find a Power BI Option-Set Xref table that contains no records.

**Comment by MscrmTools** [comment]
I guess there might be some kind of delay needed so that the table is available to create columns... I will try to fix this
