### ISSUE TITLE
Issue With Two Options Fields

### ISSUE THREAD

**Issue by odraode83** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#2]
Hello, I'm using the plugin to retrieve labels for Option Sets and Two Options Fields from my CRM Online to do some reporting with Power BI.

I can't understand why but only a few two options fields are available to be selected through the plugin, others - identically defined - two options fields are not shown by the plugin. 

Anyone can help me about?

Thanks a lot!

**Comment by MscrmTools** [comment]
Looking at the code, only OptionSets/State/Status attributes are retrieved, not Two Options attributes

**Comment by odraode83** [comment]
Thanks a lot! Are you planning to add this feature? Because, if I'm not wrong, also Two Options attributes have the same limit in retrieving a custom label from the value at the moment...

**Comment by MscrmTools** [comment]
I can add Two Options attributes if you need them

**Comment by odraode83** [comment]
That will be great!! THANKS!

**Comment by MscrmTools** [comment]
Available in the plugins store!

**Comment by odraode83** [comment]
Thank you really very much!!!
