### ISSUE TITLE
PowerBi Option Set Entity not visible in CRM Dynamics 2016 Online update 1

### ISSUE THREAD

**Issue by lagrottan** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#3]
We have been using the PowerBi option set utility in xrmtoolbox since its first release. Previously we used it with Dynamics CRM online 2015 and it seemed to work well. We have also upgraded 2015 CRM online to 2016 and it continues to work. However, when we use CRM online 2016 Update 1 as the base, the PowerBi Option set entity is not visible in CRM Dynamics online customizations, nor can PowerBi Desktop find it. We are able to connect to the correct org, and create the powerbi option set and update the values. Everything seems to work fine with no errors. However, when you go into Dynamics the entity is not there. i have now seen this multiple times on different CRM online 2016 update 1 environments.

**Comment by MscrmTools** [comment]
I do not reproduce with CRM 2016 Online Update 1... I can see the entity

**Comment by MscrmTools** [comment]
No feedback
