### ISSUE TITLE
Missing .xml file while attempting to import to CRM

### ISSUE THREAD

**Issue by Rustice** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#5]
I can´t seem to upload the OptionSet Assistant to my CRM. Can anyone tell what am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/18499237/25994647/f8beb500-370e-11e7-9d46-acd94ff7a3de.png)

**Comment by MscrmTools** [comment]
This tool is not a solution to import but a plugin for XrmToolBox
