### ISSUE TITLE
Can I do multiple option sets

### ISSUE THREAD

**Issue by achandler2033** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#6]
When I create an option set entity it saves under a name. I then use that to merge queries in power BI to show the gap_label. If I create a new option set, then it erases my old option set and causes issues with the data. 

Is there a solution for this?

Best,

Austin

**Comment by MscrmTools** [comment]
Not sure to understand exactly what the issue is. Can you be more explicit about what is erased where?
