### ISSUE TITLE
Error when creating entity

### ISSUE THREAD

**Issue by afuentes28** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#7]
![entity on powerbi](https://user-images.githubusercontent.com/52921361/67548726-2a97e300-f6c8-11e9-943a-da2ad3cebb74.png)
![error optionset](https://user-images.githubusercontent.com/52921361/67548728-2a97e300-f6c8-11e9-91bc-fc30214d2c96.png)

Hi,
I'm getting an error when creating the records for the option set selected. It says something about a missing attribute with name 'gap_value'. 
The gap_ entity is created but with only one record.
I'm attaching the image.

thanks a lot!

**Comment by InnovativeCloudSolutions-CRM** [comment]
I had the same problem.  I used this tool awhile ago successfully so I looked up the missing field.  I added a new "Whole Number" field labelled "Option Value" with a schema name of "gap_value".  Set IME Mode to disabled when creating the field.  I was then able to create the records without the error.

**Comment by MscrmTools** [comment]
So you tell me that the attribute gap_value does not exist?
It's quite strange since if something goes wrong when creating the attributes, the entity itself should be deleted to avoid keeping incomplete entity.

**Comment by InnovativeCloudSolutions-CRM** [comment]
Yes, the attribute” gap_value” was not created.  I created it manually and everything worked fine afterwards.

John Cogovan
Microsoft Dynamics IT Consultant

**Comment by gingerclaire** [comment]
Hi, First time using this and I got the following error - can anyone help explain how to fix this please (in idiots terms because I am a beginner)? I followed the instructions but I don't know what went wrong or how to fix it because I now get this error each time I try to load entities.
!
?

**Comment by MscrmTools** [comment]
Can you show the list of columns for the entity gap_PowerBIOptionsetRef?

**Comment by gingerclaire** [comment]
> Can you show the list of columns for the entity gap_PowerBIOptionsetRef?

I have an entity called: 'power BI Optenset X Ref' which seems to be the same thing and has the following fields/columns:

1. CreatedBy
2. createdon
3. createdonbehalfby
4. gap_optionsetschemaname
5. gap_powerbioptionsetrefid
6. importsequencenumber
7. modifiedby
8. modifiedon
9. modifiedonbehalfby
10. organizationid
11. overriddencreatedon
12. statecode
13. statuscode
14. timezoneruleversionnumber
15. utcconversiontimezonecode
16. versionnumber

**Comment by MscrmTools** [comment]
I just tested the tool and I was able to reproduce the error once. But it seems the issue is more about the platform metadata not being refreshed fast enough than something wrong with the tool.
After the error, if I try to create records again, it works fine. 
If I delete the entity and then ask to recreate it, it works fine.

So it seems more an issue with Dataverse than the tool itself

Please reopen the issue if you are still facing it
