### ISSUE TITLE
Data doesn't refresh

### ISSUE THREAD

**Issue by JPWCF** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#8]
I'm using PowerBI Option Set Assistant to grab option set data from Dynamics 365. For some reason newly created option sets don't refresh in Power BI when I refresh the data. is there something particular I need to do in order to get updated option sets?

**Comment by MscrmTools** [comment]
I guess you need to run this tool again as it creates/updates entity to store option sets values
