### ISSUE TITLE
All optionsets are not available for selection

### ISSUE THREAD

**Issue by jonenieminen** [MscrmTools/GapConsulting.PowerBIOptionSetAssistant#9]
When I choose entity, all optionsets of chosen entity is not listed to be selected

**Comment by jonenieminen** [comment]
I think I found out the reason. I'm looking for multiselect optionset, but tool is listing only "normal" optionsets. Any idea if there would be similar tool for multiselect optionsets?

**Comment by MscrmTools** [comment]
No, but I can maybe add support for multi select optionset

**Comment by jonenieminen** [comment]
Hi

That would be great.

Jouni

Hanki Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MscrmTools** [comment]
Should be released on Monday

**Comment by jonenieminen** [comment]
That's great. Thanks You

Hanki Outlook for Android<https://aka.ms/ghei36>

________________________________
